services:
  - type: web
    name: nexthire-utils
    runtime: node
    plan: free
    rootDir: services/utils
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nexthire-auth
    runtime: node
    plan: free
    rootDir: services/auth
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nexthire-user
    runtime: node
    plan: free
    rootDir: services/user
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nexthire-job
    runtime: node
    plan: free
    rootDir: services/job
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: nexthire-payment
    runtime: node
    plan: free
    rootDir: services/payment
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
